### PR TITLE
Fixing issues with SSL; adding facade; replacing S3 library

### PR DESCRIPTION
**Pull request by callovarne**
This fixes issues with SSL when the bucket name contains dots. I've removed the dusty S3 library in favor of the AWS Phar and added a facade in front of it. The Phar is a bit big, so feel free to dig into the SDK and pull out only what's needed for S3. :D

### CODE REVIEW

**Comment by callovarne** [comment]
Almost forgot...I think this addresses #19.

**Comment by nitriques** [comment]
+1 for the facade.

Can you create a new minor version in the meta.xml file please ?

**Comment by michael-e** [comment]
Sorry that I haven't cared for #19 myself. Meanwhile I have decided to leave AWS completely instead of using it even more. The main reason is the unability/reluctance of certain governments to understand any concerns regarding mass surveillance. (American companies don't understand it either, for the most part.)

One question regarding the PR: Should we include the AWS lib as phar file (like in the pull request) or should we rather use composer? @nitriques, what do you think?

**Comment by nitriques** [comment]
@michael-e I do not mind the phar nor composer: but I want to be able to git clone and everything must work.

**Comment by michael-e** [comment]
Nor do I, but I think we should somehow include the version number of the phar file in the meta.xml file.

**Comment by nitriques** [comment]
>  include the version number of the phar file in the meta.xml file.

Definitely. Ideally in this: http://symphonyextensions.com/schemas/extension/1.0/#dependencies

**Comment by michael-e** [comment]
Yep, nice idea, but "dependency" sounds a bit like something that must be met by the developer when installing the extension. We might instead just use plain text in the release information.

**Comment by nitriques** [comment]
> We might instead just use plain text in the release information.

Yeah you're right.

**Comment by michael-e** [comment]
@callovarne: Can you please add the version/release info (including the version of the AWS library) to the meta.xml file and add a commit to your branch for the pull request? (If you don't find the time, just tell us — we will do it then.) And, last but not least: thanks for your work on this!

**Comment by callovarne** [comment]
Please pardon the delay...got buried. :shit:

**Comment by brendo** [comment]
The `integration` branch now has these changes rolled in.

I disagree that the dependency needs to be included in the `meta.xml` file. If it's provided by this extension (which it is), there's no need.

Many thanks @callovarne :)

**Comment by michael-e** [comment]
> Many thanks @callovarne :)

+1

**Pull request closed without merging**
